window.catalog = [{
    id: '0',
    dateAdded: '2017-05-15T16:58:40.000Z',
    title: 'Филадельфия',
    description: 'The best food for you and your friends.Филадельфия',
    placeholder: null,
    discountedPrice: 24.75,
    price: 24.75,
    popularity: 1,
    hasNew: true,
    category: ['пицца', 'presentation'],
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg' // replace with paths to images extracted from item layout
},{
    id: '1',
    dateAdded: '2017-05-15T16:58:40.000Z',
    title: 'Филадельфия',
    description: 'The best food for you and your friends.Филадельфия',
    placeholder: null,
    discountedPrice: 24.75,
    price: 24.75,
    popularity: 1,
    hasNew: true,
    category: ['пицца', 'presentation'],
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg' // replace with paths to images extracted from item layout
}, {
    id: '22',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 30,
    price: 30,
    popularity: 2,
    hasNew: true,
    category: ['суши-2', 'presentation'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-суши-2.jpg', // replace with image extracted from item layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '3',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 35.75,
    price: 35.75,
    popularity: 3,
    hasNew: true,
    category: ['суши' , 'presentation'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-common.jpg', // replace with image extracted from item layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '4',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 4,
    hasNew: true,
    category: ['суши' , 'presentation'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-common.jpg', // replace with image extracted from item layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '5',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 5,
    hasNew: true,
    category: ['суши-2' , 'presentation'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-суши-2.jpg', // replace with image extracted from item layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '6',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 6,
    hasNew: true, //новинка false - нет, true - да
    category: ['пицца', 'best-sellers'], //категории и подкатегории
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад', // вес сэта
    size: 8, //сколько штук в сэте
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg' // replace with paths to images extracted from item layout
}, {
    id: '7',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 7,
    hasNew: true,
    category: ['пицца'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg' // replace with paths to images extracted from item layout
}, {
    id: '8',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 8,
    hasNew: false,
    category: ['пицца'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg' // replace with paths to images extracted from item layout
}, {
    id: '9',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 9,
    hasNew: false,
    category: ['best-sellers', 'пицца'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg' // replace with paths to images extracted from item layout
}, {
    id: '10',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '11',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
},
{
    id: '12',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['напитки'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-напитки.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-drink.jpg', // replace with paths to images extracted from item layout
}, {
    id: '13',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: false,
    category: ['напитки'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-напитки.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-drink.jpg' // replace with paths to images extracted from item layout
}, {
    id: '14',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['пицца'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg', // replace with paths to images extracted from item layout
},
{
    id: '15',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg',
}, {
    id: '16',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: false,
    category: ['напитки'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-напитки.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-drink.jpg',
}, {
    id: '17',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg',
}, 
{
    id: '18',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg',
}, {
    id: '19',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: true,
    category: ['пицца', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big-pizza.jpg',
}, {
    id: '20',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: true,
    category: ['суши-2', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg',
},
{
    id: '21',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg',
}, {
    id: '2',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 10,
    price: 120,
    popularity: 1,
    hasNew: true,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
}, {
    id: '23',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши', 'best-sellers'],
    info: {},
    weight: 400,
    info: {'калорий':'320','калорий':'320','гр. рыбы':'320','гр. риса':'320', 'процент':'50%', 'гр. майонеза': '10'},
    ingredients: 'Копченый угорь, икра корюшки и огурец, обернутые в слайсы из авокад',
    size: 8,
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    imgFull: 'img/item-big.jpg' // replace with paths to images extracted from item layout
},];


window.catalog.sort(function(a,b){
    return a.id - b.id;
})
