window.catalog = [{
    id: '1',
    dateAdded: '2017-05-15T16:58:40.000Z',
    title: 'Monki Festival Knitted Monki Festival Knitted',
    description: 'The best food for you and your friends.Monki Festival Knitted Monki Festival Knitted',
    placeholder: null,
    discountedPrice: 24.75,
    price: 24.75,
    popularity: 1,
    hasNew: false,
    category: ['пицца', 'presentation'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-1.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '2',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 30,
    price: 30,
    popularity: 2,
    hasNew: false,
    category: ['суши-2', 'presentation'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-суши-2.jpg', // replace with image extracted from item layout
    preview: ['img/item-2.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '3',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 35.75,
    price: 35.75,
    popularity: 3,
    hasNew: false,
    category: ['суши' , 'presentation'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-common.jpg', // replace with image extracted from item layout
    preview: ['img/item-3.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '4',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 4,
    hasNew: false,
    category: ['суши' , 'presentation'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-common.jpg', // replace with image extracted from item layout
    preview: ['img/item-2.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '5',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 5,
    hasNew: false,
    category: ['суши-2' , 'presentation'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-суши-2.jpg', // replace with image extracted from item layout
    preview: ['img/item-3.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '6',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 6,
    hasNew: false,
    category: ['пицца', 'best-sellers'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-2.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '7',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 7,
    hasNew: false,
    category: ['пицца'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-3.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '8',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 8,
    hasNew: false,
    category: ['пицца'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-2.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '9',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 9,
    hasNew: false,
    category: ['best-sellers', 'пицца'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-3.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '10',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-2.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '11',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-3.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
},
{
    id: '12',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['напитки'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-напитки.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-3.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '13',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: false,
    category: ['напитки'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-напитки.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-2.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '14',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['пицца'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg', // replace with paths to images extracted from item layout
},
{
    id: '15',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg'
}, {
    id: '16',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: false,
    category: ['напитки'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-напитки.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg'
}, {
    id: '17',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши-2'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg'
}, 
{
    id: '18',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg'
}, {
    id: '19',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 90,
    price: 120,
    popularity: 1,
    hasNew: true,
    category: ['пицца', 'best-sellers'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-пицца.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg'
}, {
    id: '20',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: true,
    category: ['суши-2', 'best-sellers'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-суши-2.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg'
},
{
    id: '21',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши', 'best-sellers'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    thumbnailFull: 'img/item-full.jpg'
}, {
    id: '22',
    dateAdded: '2017-06-12T15:35:13.000Z',
    title: 'The best food for you and your friends',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 10,
    price: 120,
    popularity: 1,
    hasNew: true,
    category: ['суши', 'best-sellers'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-2.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
}, {
    id: '23',
    dateAdded: '2017-02-12T11:14:29.000Z',
    title: 'суши set Philadelphia',
    description: 'The best food for you and your friends',
    placeholder: null,
    discountedPrice: 85.75,
    price: 85.75,
    popularity: 1,
    hasNew: false,
    category: ['суши', 'best-sellers'],
    fashion: 'Casual style',
    colors: [],
    sizes: [],
    thumbnail: 'img/item-common.jpg', // replace with path to image extracted from catalog layout
    preview: ['img/item-3.jpg', 'full image path 2', 'full image path 3'] // replace with paths to images extracted from item layout
},];
